services:
  postgres:
    image: postgres:15-alpine
    container_name: mealplanner-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Baseball28
      POSTGRES_DB: mealplanner
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

