
//GetAll
GET http://localhost:5151/api/meals

### 

//GetById
GET http://localhost:5151/api/meals/1

###

//UpdateById
PATCH http://localhost:5151/api/meals/1

###

//DeleteById
DELETE http://localhost:5151/api/meals/1