@baseURL = http://localhost:5151

//___________________________________________________________________
//Meals
//___________________________________________________________________
@currentMealId = 019cd14c-594f-7a22-8e4c-c0d65b27c0a8


//GetAll
GET {{baseURL}}/api/meals
### 

//GetById
GET {{baseURL}}/api/meals/{{currentMealId}}
###

//CreateMeal
POST {{baseURL}}/api/meals HTTP/1.1
Content-Type: application/json

{
  "name": "Chicken Stir Fry",
  "serving_calories": 450,
  "instructions": "Heat oil in a pan, cook chicken, add vegetables, and stir fry for 5 minutes.",
  "user_id": "019becb7-f86b-749c-b417-79e99405c7c8",
  "ingredients": [
    { "name": "Chicken breast", "quantity": 2, "unit": "pieces" },
    { "name": "Soy sauce", "quantity": 3, "unit": "tbsp" },
    { "name": "Broccoli", "quantity": 1, "unit": "cup" },
    { "name": "Garlic", "quantity": 2, "unit": "cloves" },
    { "name": "Olive oil", "quantity": 2, "unit": "tbsp" }
  ]
}
###

//UpdateById
PATCH {{baseURL}}/api/meals/{{currentMealId}}
###

//DeleteById
DELETE {{baseURL}}/api/meals/{{currentMealId}}
###

//___________________________________________________________________
//Users
//___________________________________________________________________
@userEmail = "alice@example.com"
@userName = "Alice"
@currentUserId = 019ccf44-1e33-77aa-b1dc-fa47e910bd80


//GetAll
GET {{baseURL}}/api/users
###

//GetUserById
GET {{baseURL}}/api/users/{{currentUserId}}
###

//CreateUser
POST {{baseURL}}/api/users
Content-Type: application/json

{
  "name": {{userName}},
  "email": {{userEmail}}
}
###

//UpdateUser
PATCH {{baseURL}}/api/users/{{currentUserId}}
Content-Type: application/json

{
    "name": "Karen",
    "email": "AliceToKaren@example.com"
}
###

//DeleteUser
DELETE {{baseURL}}/api/users/{{currentUserId}}
###